### ISSUE TITLE
Deployment to several rpis

### ISSUE THREAD

**Issue by gylead** [chschnell/build-qt5-rpi#5]
I have several identical rpis and would like to install Qt 5 on all of them. It would be nice to have a command "deploy" which just deploys the qt packages to a rpi that is named in the command line.

**Comment by chschnell** [comment]
Please see the new release I just committed.

One of the things new is that the script now generates two `.deb` installers instead of the somewhat loose-end approach from before. Once you've build the two installers you can deploy them to any number of arm devices (and build hosts).

Cheers and let me know if it works,
Christian
